name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  bloc: ^8.1.4
  connectivity_plus: ^6.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  geolocator: ^13.0.1
  http: ^1.2.2
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.19.0
  open_settings_plus: ^0.3.3
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
